
package com.clt.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HelloWebservice", targetNamespace = "http://ws.clt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HelloWebservice {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doSomething", targetNamespace = "http://ws.clt.com/", className = "com.clt.ws.DoSomething")
    @ResponseWrapper(localName = "doSomethingResponse", targetNamespace = "http://ws.clt.com/", className = "com.clt.ws.DoSomethingResponse")
    @Action(input = "http://ws.clt.com/HelloWebservice/doSomethingRequest", output = "http://ws.clt.com/HelloWebservice/doSomethingResponse")
    public String doSomething(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetLoginUserInfo")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "GetLoginUserInfo", targetNamespace = "http://ws.clt.com/", className = "com.clt.ws.GetLoginUserInfo")
    @ResponseWrapper(localName = "GetLoginUserInfoResponse", targetNamespace = "http://ws.clt.com/", className = "com.clt.ws.GetLoginUserInfoResponse")
    @Action(input = "http://ws.clt.com/HelloWebservice/GetLoginUserInfoRequest", output = "http://ws.clt.com/HelloWebservice/GetLoginUserInfoResponse")
    public String getLoginUserInfo(
            @WebParam(name = "arg0", targetNamespace = "")
                    String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
                    String arg1);

}
